-- M4 Stage 2B.1: database primitives only. No participant or agent path uses these yet.
-- Bearer tokens are generated by trusted application code; only their hashes are stored.

-- Existing fixtures may predate canonical event keys. Preserve them without changing
-- their evidence IDs, then require a stable key for every future message.
update public.messages
set transport_segment_id = 'legacy:' || id::text
where transport_segment_id is null;
alter table public.messages alter column transport_segment_id set not null;
alter table public.messages add constraint messages_event_key_nonempty
  check (char_length(btrim(transport_segment_id)) between 1 and 200);
alter table public.messages add column interrupted boolean not null default false;

-- The existing conversation is the lifecycle and ordering authority.
alter table public.conversations drop constraint conversations_status_check;
alter table public.conversations add constraint conversations_status_check
  check (status in ('pending', 'in_progress', 'interrupted', 'completed', 'cancelled', 'failed'));
alter table public.conversations alter column status set default 'pending';
alter table public.conversations add column consented_at timestamptz;
alter table public.conversations add column consent_version text
  check (consent_version is null or char_length(btrim(consent_version)) between 1 and 80);
alter table public.conversations add column interrupted_at timestamptz;
alter table public.conversations add column writer_generation bigint not null default 0
  check (writer_generation >= 0);
alter table public.conversations add column next_message_sequence integer not null default 0
  check (next_message_sequence >= 0);
update public.conversations c
set next_message_sequence = coalesce((
  select max(m.sequence) + 1 from public.messages m where m.conversation_id = c.id
), 0);
update public.conversations set interrupted_at = updated_at where status = 'interrupted';
alter table public.conversations add constraint conversations_consent_pair
  check ((consented_at is null) = (consent_version is null));
alter table public.conversations add constraint conversations_active_requires_consent
  check (status not in ('in_progress', 'interrupted', 'completed') or consented_at is not null);
alter table public.conversations add constraint conversations_interrupt_timestamp
  check ((status = 'interrupted') = (interrupted_at is not null));
alter table public.conversations add constraint conversations_terminal_timestamp
  check ((status in ('completed', 'cancelled', 'failed')) = (ended_at is not null));

create function private.guard_conversation_lifecycle()
returns trigger language plpgsql set search_path = '' as $$
begin
  if old.consented_at is not null and
     (new.consented_at is distinct from old.consented_at or
      new.consent_version is distinct from old.consent_version) then
    raise exception 'conversation consent is immutable' using errcode = 'check_violation';
  end if;
  if new.writer_generation < old.writer_generation or
     new.next_message_sequence < old.next_message_sequence then
    raise exception 'conversation counters cannot move backward' using errcode = 'check_violation';
  end if;
  if new.status is distinct from old.status and not (
    (old.status = 'pending' and new.status in ('in_progress', 'cancelled', 'failed')) or
    (old.status = 'in_progress' and new.status in ('interrupted', 'completed', 'cancelled', 'failed')) or
    (old.status = 'interrupted' and new.status in ('in_progress', 'completed', 'cancelled', 'failed'))
  ) then
    raise exception 'invalid conversation status transition: % to %', old.status, new.status
      using errcode = 'check_violation';
  end if;
  if new.status in ('in_progress', 'interrupted', 'completed') and new.consented_at is null then
    raise exception 'transcript consent is required before an interview begins'
      using errcode = 'check_violation';
  end if;
  return new;
end;
$$;
create trigger conversations_guard_lifecycle before update on public.conversations
  for each row execute function private.guard_conversation_lifecycle();

-- Invitations are single-use study-scoped capabilities. This metadata is never
-- exposed through the Data API to participants or researchers.
create table public.interview_invitations (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null,
  study_id uuid not null,
  issued_by uuid not null references public.profiles(id),
  token_hash text not null unique check (token_hash ~ '^[0-9a-f]{64}$'),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '7 days'),
  revoked_at timestamptz,
  claimed_at timestamptz,
  conversation_id uuid unique,
  foreign key (study_id, workspace_id) references public.studies(id, workspace_id) on delete cascade,
  foreign key (conversation_id, study_id, workspace_id)
    references public.conversations(id, study_id, workspace_id) on delete cascade,
  check (expires_at > created_at and expires_at <= created_at + interval '7 days'),
  check ((claimed_at is null) = (conversation_id is null)),
  check (revoked_at is null or revoked_at >= created_at)
);
create index interview_invitations_study_idx
  on public.interview_invitations(study_id, created_at desc);
create index interview_invitations_unclaimed_idx
  on public.interview_invitations(expires_at) where claimed_at is null and revoked_at is null;

-- A separate hashed bearer after claim. At most one active resume capability
-- per conversation; rotation revokes the old row before a replacement is added.
create table public.interview_resumes (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  token_hash text not null unique check (token_hash ~ '^[0-9a-f]{64}$'),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours'),
  revoked_at timestamptz,
  check (expires_at > created_at and expires_at <= created_at + interval '24 hours'),
  check (revoked_at is null or revoked_at >= created_at)
);
create unique index interview_resumes_one_active_per_conversation
  on public.interview_resumes(conversation_id) where revoked_at is null;

create function private.guard_invitation()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if tg_op = 'INSERT' then
    if not exists (
      select 1 from public.workspace_members m
      where m.workspace_id = new.workspace_id and m.user_id = new.issued_by
    ) then
      raise exception 'invitation issuer must belong to the study workspace'
        using errcode = 'insufficient_privilege';
    end if;
  elsif new.workspace_id is distinct from old.workspace_id or
        new.study_id is distinct from old.study_id or
        new.issued_by is distinct from old.issued_by or
        new.token_hash is distinct from old.token_hash or
        new.expires_at is distinct from old.expires_at or
        new.created_at is distinct from old.created_at or
        (old.claimed_at is not null and (new.claimed_at is distinct from old.claimed_at or
          new.conversation_id is distinct from old.conversation_id)) or
        (old.revoked_at is not null and new.revoked_at is distinct from old.revoked_at) then
    raise exception 'invitation scope and claims cannot be rewritten'
      using errcode = 'check_violation';
  end if;
  return new;
end;
$$;
create trigger interview_invitations_guard before insert or update on public.interview_invitations
  for each row execute function private.guard_invitation();

-- Issued means the trusted engine committed the exact action before sending it.
-- Rendered means the participant client later acknowledged rendering it.
alter table public.visual_displays rename column shown_at to issued_at;
alter table public.visual_displays add column rendered_at timestamptz;
alter table public.visual_displays add constraint visual_render_after_issue
  check (rendered_at is null or rendered_at >= issued_at);
drop trigger visual_displays_are_immutable on public.visual_displays;
create function private.guard_display_render()
returns trigger language plpgsql set search_path = '' as $$
begin
  if old.rendered_at is not null or new.rendered_at is null or
     (to_jsonb(new) - 'rendered_at') <> (to_jsonb(old) - 'rendered_at') then
    raise exception 'raw evidence in visual_displays is immutable except one render receipt'
      using errcode = 'restrict_violation';
  end if;
  return new;
end;
$$;
create trigger visual_displays_guard_render before update on public.visual_displays
  for each row execute function private.guard_display_render();

-- A structured answer is valid only after a client render receipt. Keep the
-- Stage 1 option/value checks and add this stronger provenance condition.
create function private.require_rendered_display()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if not exists (
    select 1 from public.visual_displays d
    where d.id = new.display_id and d.conversation_id = new.conversation_id
      and d.rendered_at is not null
  ) then
    raise exception 'visual response requires a rendered display'
      using errcode = 'check_violation';
  end if;
  return new;
end;
$$;
create trigger visual_responses_require_render before insert on public.visual_responses
  for each row execute function private.require_rendered_display();

alter table public.interview_invitations enable row level security;
alter table public.interview_resumes enable row level security;
revoke all on public.interview_invitations, public.interview_resumes from anon, authenticated;
grant select, insert, update, delete on public.interview_invitations, public.interview_resumes to service_role;

-- A claim is one transaction: consume the invitation, create the pseudonymous
-- participant and pending conversation, and install a distinct resume hash.
-- The caller supplies only hashed capabilities and a server-generated room name.
create function public.claim_interview_invitation(
  p_invitation_hash text, p_resume_hash text, p_livekit_room text, p_consent_version text
)
returns uuid language plpgsql security definer set search_path = '' as $$
declare
  invitation public.interview_invitations%rowtype;
  participant_id uuid := gen_random_uuid();
  created_conversation uuid;
begin
  if p_invitation_hash !~ '^[0-9a-f]{64}$' or p_resume_hash !~ '^[0-9a-f]{64}$' or
     p_invitation_hash = p_resume_hash or
     char_length(btrim(coalesce(p_consent_version, ''))) not between 1 and 80 or
     char_length(btrim(coalesce(p_livekit_room, ''))) not between 1 and 200 then
    raise exception 'invalid interview claim' using errcode = 'check_violation';
  end if;
  select * into invitation from public.interview_invitations
    where token_hash = p_invitation_hash for update;
  if not found or invitation.claimed_at is not null or invitation.revoked_at is not null or
     invitation.expires_at <= clock_timestamp() or not exists (
       select 1 from public.studies s where s.id = invitation.study_id and
         s.workspace_id = invitation.workspace_id and s.status = 'active'
     ) then
    raise exception 'invitation is unavailable' using errcode = 'insufficient_privilege';
  end if;
  insert into public.participants(id, workspace_id, study_id, alias)
  values (participant_id, invitation.workspace_id, invitation.study_id,
          'Participant ' || participant_id::text);
  insert into public.conversations(workspace_id, study_id, participant_id,
                                   livekit_room, status, consented_at, consent_version)
  values (invitation.workspace_id, invitation.study_id, participant_id,
          p_livekit_room, 'pending', clock_timestamp(), p_consent_version)
  returning id into created_conversation;
  insert into public.interview_resumes(conversation_id, token_hash)
  values (created_conversation, p_resume_hash);
  update public.interview_invitations
    set claimed_at = clock_timestamp(), conversation_id = created_conversation
    where id = invitation.id;
  return created_conversation;
end;
$$;

create function public.resolve_interview_resume(p_resume_hash text)
returns uuid language plpgsql security definer set search_path = '' as $$
declare found_conversation uuid;
begin
  select r.conversation_id into found_conversation
  from public.interview_resumes r
  join public.conversations c on c.id = r.conversation_id
  where r.token_hash = p_resume_hash and r.revoked_at is null
    and r.expires_at > clock_timestamp()
    and (c.status in ('pending', 'in_progress') or
         (c.status = 'interrupted' and c.interrupted_at > clock_timestamp() - interval '24 hours'));
  return found_conversation;
end;
$$;

-- New agent jobs fence old jobs. A reconnect to the same live job does not call
-- this RPC; a replacement receives a larger generation.
create function public.claim_conversation_writer(p_conversation_id uuid, p_livekit_room text)
returns bigint language plpgsql security definer set search_path = '' as $$
declare c public.conversations%rowtype;
begin
  select * into c from public.conversations where id = p_conversation_id for update;
  if not found or c.livekit_room is distinct from p_livekit_room or c.consented_at is null or
     not (c.status = 'pending' or c.status = 'in_progress' or
       (c.status = 'interrupted' and c.interrupted_at > clock_timestamp() - interval '24 hours')) then
    raise exception 'conversation cannot accept a writer' using errcode = 'insufficient_privilege';
  end if;
  update public.conversations
  set writer_generation = writer_generation + 1,
      status = 'in_progress', interrupted_at = null
  where id = p_conversation_id
  returning writer_generation into c.writer_generation;
  return c.writer_generation;
end;
$$;

create function public.transition_interview_conversation(
  p_conversation_id uuid, p_writer_generation bigint, p_next_status text
)
returns text language plpgsql security definer set search_path = '' as $$
declare c public.conversations%rowtype;
begin
  select * into c from public.conversations where id = p_conversation_id for update;
  if not found or c.writer_generation <> p_writer_generation then
    raise exception 'stale conversation writer' using errcode = 'insufficient_privilege';
  end if;
  if c.status = p_next_status then return c.status; end if;
  -- The trigger below enforces the permitted transition graph for every role.
  update public.conversations set status = p_next_status,
      interrupted_at = case when p_next_status = 'interrupted' then clock_timestamp() else null end,
      ended_at = case when p_next_status in ('completed', 'cancelled', 'failed')
                      then clock_timestamp() else null end
  where id = p_conversation_id;
  return p_next_status;
end;
$$;

create function public.append_interview_message(
  p_conversation_id uuid, p_writer_generation bigint, p_event_key text,
  p_speaker text, p_channel text, p_content text, p_occurred_at timestamptz,
  p_interrupted boolean default false
)
returns table(message_id uuid, message_sequence integer, inserted boolean)
language plpgsql security definer set search_path = '' as $$
declare c public.conversations%rowtype; existing public.messages%rowtype; allocated integer;
begin
  select * into c from public.conversations where id = p_conversation_id for update;
  if not found or c.writer_generation <> p_writer_generation or c.consented_at is null then
    raise exception 'conversation is not writable by this generation'
      using errcode = 'insufficient_privilege';
  end if;
  if p_channel = 'visual' then
    raise exception 'visual messages require the atomic visual-response operation'
      using errcode = 'check_violation';
  end if;
  select * into existing from public.messages m
    where m.conversation_id = p_conversation_id and m.transport_segment_id = p_event_key;
  if found then
    if existing.speaker is distinct from p_speaker or existing.channel is distinct from p_channel or
       existing.content is distinct from p_content or existing.occurred_at is distinct from p_occurred_at or
       existing.interrupted is distinct from p_interrupted then
      raise exception 'event key reused with conflicting payload' using errcode = 'unique_violation';
    end if;
    return query select existing.id, existing.sequence, false;
    return;
  end if;
  if c.status <> 'in_progress' then
    raise exception 'conversation is not writable by this generation'
      using errcode = 'insufficient_privilege';
  end if;
  update public.conversations set next_message_sequence = next_message_sequence + 1
    where id = p_conversation_id returning next_message_sequence - 1 into allocated;
  return query
    insert into public.messages(workspace_id, study_id, conversation_id, sequence,
      speaker, channel, content, occurred_at, transport_segment_id, interrupted)
    values (c.workspace_id, c.study_id, p_conversation_id, allocated,
      p_speaker, p_channel, p_content, p_occurred_at, p_event_key, p_interrupted)
    returning id, sequence, true;
end;
$$;

create function public.issue_interview_visual(
  p_conversation_id uuid, p_writer_generation bigint, p_definition jsonb
)
returns uuid language plpgsql security definer set search_path = '' as $$
declare c public.conversations%rowtype; existing public.visual_displays%rowtype; created uuid;
begin
  select * into c from public.conversations where id = p_conversation_id for update;
  if not found or c.writer_generation <> p_writer_generation or c.consented_at is null then
    raise exception 'conversation is not writable by this generation'
      using errcode = 'insufficient_privilege';
  end if;
  select * into existing from public.visual_displays d
    where d.conversation_id = p_conversation_id and d.action_id = p_definition ->> 'id';
  if found then
    if existing.definition <> p_definition then
      raise exception 'visual action id reused with conflicting payload' using errcode = 'unique_violation';
    end if;
    return existing.id;
  end if;
  insert into public.visual_displays(workspace_id, study_id, conversation_id,
    action_id, visual_type, prompt, definition, issued_at)
  values(c.workspace_id, c.study_id, p_conversation_id, p_definition ->> 'id',
    p_definition ->> 'type', p_definition ->> 'prompt', p_definition, clock_timestamp())
  returning id into created;
  return created;
end;
$$;

create function public.acknowledge_interview_visual(
  p_conversation_id uuid, p_writer_generation bigint, p_action_id text
)
returns uuid language plpgsql security definer set search_path = '' as $$
declare c public.conversations%rowtype; d public.visual_displays%rowtype;
begin
  select * into c from public.conversations where id = p_conversation_id for update;
  if not found or c.writer_generation <> p_writer_generation or c.status <> 'in_progress' then
    raise exception 'conversation is not writable by this generation'
      using errcode = 'insufficient_privilege';
  end if;
  select * into d from public.visual_displays
    where conversation_id = p_conversation_id and action_id = p_action_id for update;
  if not found then raise exception 'visual action not issued' using errcode = 'no_data_found'; end if;
  if d.rendered_at is null then
    update public.visual_displays set rendered_at = clock_timestamp() where id = d.id;
  end if;
  return d.id;
end;
$$;

create function public.append_interview_visual_response(
  p_conversation_id uuid, p_writer_generation bigint, p_event_key text,
  p_action_id text, p_content text, p_occurred_at timestamptz,
  p_selected_option_ids text[] default '{}', p_numeric_value numeric default null
)
returns table(message_id uuid, message_sequence integer, inserted boolean)
language plpgsql security definer set search_path = '' as $$
declare c public.conversations%rowtype; d public.visual_displays%rowtype;
  existing public.messages%rowtype; answer public.visual_responses%rowtype;
  allocated integer; created uuid;
begin
  select * into c from public.conversations where id = p_conversation_id for update;
  if not found or c.writer_generation <> p_writer_generation or c.status <> 'in_progress' or
     c.consented_at is null then
    raise exception 'conversation is not writable by this generation'
      using errcode = 'insufficient_privilege';
  end if;
  select * into d from public.visual_displays
    where conversation_id = p_conversation_id and action_id = p_action_id and rendered_at is not null;
  if not found then raise exception 'visual action was not rendered' using errcode = 'check_violation'; end if;
  select * into existing from public.messages m
    where m.conversation_id = p_conversation_id and m.transport_segment_id = p_event_key;
  if found then
    select * into answer from public.visual_responses v where v.message_id = existing.id;
    if existing.speaker <> 'participant' or existing.channel <> 'visual' or
       existing.content is distinct from p_content or existing.occurred_at is distinct from p_occurred_at or
       answer.display_id is distinct from d.id or
       answer.selected_option_ids is distinct from p_selected_option_ids or
       answer.numeric_value is distinct from p_numeric_value then
      raise exception 'event key reused with conflicting visual answer'
        using errcode = 'unique_violation';
    end if;
    return query select existing.id, existing.sequence, false;
    return;
  end if;
  if c.status <> 'in_progress' then
    raise exception 'conversation is not writable by this generation'
      using errcode = 'insufficient_privilege';
  end if;
  update public.conversations set next_message_sequence = next_message_sequence + 1
    where id = p_conversation_id returning next_message_sequence - 1 into allocated;
  insert into public.messages(workspace_id, study_id, conversation_id, sequence,
    speaker, channel, content, occurred_at, transport_segment_id)
  values(c.workspace_id, c.study_id, p_conversation_id, allocated,
    'participant', 'visual', p_content, p_occurred_at, p_event_key)
  returning id into created;
  insert into public.visual_responses(workspace_id, study_id, conversation_id,
    display_id, message_id, visual_type, selected_option_ids, numeric_value)
  values(c.workspace_id, c.study_id, p_conversation_id,
    d.id, created, d.visual_type, p_selected_option_ids, p_numeric_value);
  return query select created, allocated, true;
end;
$$;

-- Supabase normally grants new public functions to PUBLIC. These functions
-- carry elevated database authority and are callable only with service_role.
revoke all on function public.claim_interview_invitation(text,text,text,text) from public, anon, authenticated;
revoke all on function public.resolve_interview_resume(text) from public, anon, authenticated;
revoke all on function public.claim_conversation_writer(uuid,text) from public, anon, authenticated;
revoke all on function public.transition_interview_conversation(uuid,bigint,text) from public, anon, authenticated;
revoke all on function public.append_interview_message(uuid,bigint,text,text,text,text,timestamptz,boolean) from public, anon, authenticated;
revoke all on function public.issue_interview_visual(uuid,bigint,jsonb) from public, anon, authenticated;
revoke all on function public.acknowledge_interview_visual(uuid,bigint,text) from public, anon, authenticated;
revoke all on function public.append_interview_visual_response(uuid,bigint,text,text,text,timestamptz,text[],numeric) from public, anon, authenticated;
grant execute on function public.claim_interview_invitation(text,text,text,text) to service_role;
grant execute on function public.resolve_interview_resume(text) to service_role;
grant execute on function public.claim_conversation_writer(uuid,text) to service_role;
grant execute on function public.transition_interview_conversation(uuid,bigint,text) to service_role;
grant execute on function public.append_interview_message(uuid,bigint,text,text,text,text,timestamptz,boolean) to service_role;
grant execute on function public.issue_interview_visual(uuid,bigint,jsonb) to service_role;
grant execute on function public.acknowledge_interview_visual(uuid,bigint,text) to service_role;
grant execute on function public.append_interview_visual_response(uuid,bigint,text,text,text,timestamptz,text[],numeric) to service_role;
